# Configuration for readthedocs
# Doc: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Only compile HTML
formats: []

python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs

sphinx:
   configuration: docs/source/conf.py
